# Generated by Django 3.2.4 on 2021-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category__name'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['name'], name='news__name'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['name', '-created_at'], name='news__name__created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['name', '-updated_at'], name='news__name__updated_at_desc'),
        ),
    ]
