# Generated by Django 3.2.3 on 2021-06-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210603_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_group_id',
            new_name='menu_group',
        ),
    ]
