# Generated by Django 3.2.4 on 2021-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('thumbnail_url', models.CharField(default=0, max_length=255, null=True)),
                ('attachable_id', models.IntegerField(default=0, null=True)),
                ('attachable_type', models.CharField(default=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
