# Generated by Django 3.2.4 on 2021-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['attachable_id'], name='attachement_attachable_id'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['attachable_type'], name='attachement_attachable_type'),
        ),
    ]
