# Generated by Django 3.2.4 on 2021-06-03 19:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
